import { SchoolProvider } from '../provider.types'

export const wtbuProvider: SchoolProvider = {
  id: 'wtbu',
  meta: {
    id: 'wtbu',
    name: '武汉工商学院',
    shortName: '武工商',
    providerId: 'wtbu',
    loginMode: 'direct_password',
    eduSystemType: 'eams',
    status: 'enabled',
    verifiedAt: '2026-06-12T00:00:00.000Z',
    capabilities: { course: true, score: true, exam: true, profile: true },
    credentialSave: {
      passwordVaultAllowed: true,
      autoSync: 'password_login',
      scheduledSyncSupported: true,
      title: '支持保存登录信息',
      notice:
        '保存教务账号密码后，可通过云函数完成首次导入和后续自动同步。账号密码会加密保存在后端，不会用于后端直连学校系统。',
      consentLabel: '加密保存账号密码，用于自动同步',
    },
    dataAccess: {
      course: ['cloud_worker', 'webview_client_fetch', 'manual_import'],
      score: ['cloud_worker', 'webview_client_fetch', 'manual_import'],
      exam: ['cloud_worker', 'webview_client_fetch', 'manual_import'],
      profile: ['cloud_worker', 'webview_client_fetch', 'manual_import'],
    },
    featureDisplay: {
      course: {
        title: '课表',
        kind: 'course_grid',
        itemFields: [
          { key: 'name', label: '课程', primary: true },
          { key: 'teacher', label: '教师' },
          { key: 'classroom', label: '教室', fallbackKeys: ['location'] },
          { key: 'weeks', label: '周次' },
        ],
        itemPath: 'courses',
        emptyText: '暂无课表数据',
      },
      score: {
        title: '成绩',
        kind: 'score_semesters',
        summaryFields: [
          { key: 'totalCredit', label: '总学分' },
          { key: 'average', label: '平均分' },
          { key: 'gpa', label: '绩点' },
        ],
        groupPath: 'semesters',
        itemPath: 'grades',
        itemFields: [
          { key: 'name', label: '课程' },
          { key: 'credit', label: '学分' },
          { key: 'score', label: '成绩', primary: true },
          { key: 'gpa', label: '绩点' },
        ],
        emptyText: '暂无成绩缓存',
      },
      exam: {
        title: '考试',
        kind: 'exam_list',
        emptyText: '暂无考试安排',
      },
      profile: {
        title: '个人资料',
        kind: 'profile_fields',
        summaryFields: [
          { key: 'name', label: '姓名' },
          { key: 'maskedStudentId', label: '学号', fallbackKeys: ['studentId'] },
          { key: 'major', label: '专业' },
          { key: 'className', label: '班级' },
          { key: 'level', label: '层次', fallbackKeys: ['grade'] },
        ],
        detailFields: [
          { key: 'studentId', label: '学号', editable: false },
          { key: 'grade', label: '年级', editable: true },
          { key: 'gender', label: '性别', editable: true },
          { key: 'phone', label: '手机号', editable: true },
          { key: 'email', label: '邮箱', editable: true },
          { key: 'nativePlace', label: '籍贯', editable: true },
          { key: 'enrollmentDate', label: '入学时间', editable: true },
          { key: 'studentStatus', label: '学籍状态', editable: true },
          { key: 'dormitory', label: '宿舍信息', editable: true },
          { key: 'counselor', label: '辅导员', editable: true },
        ],
        editableFields: [
          { key: 'name', label: '姓名' },
          { key: 'major', label: '专业' },
          { key: 'grade', label: '年级' },
          { key: 'level', label: '层次' },
          { key: 'className', label: '班级' },
          { key: 'gender', label: '性别' },
          { key: 'birthDate', label: '出生年月' },
          { key: 'politicalStatus', label: '政治面貌' },
          { key: 'phone', label: '手机号' },
          { key: 'email', label: '邮箱' },
          { key: 'nativePlace', label: '籍贯' },
          { key: 'enrollmentDate', label: '入学时间' },
          { key: 'studentStatus', label: '学籍状态' },
          { key: 'dormitory', label: '宿舍信息' },
          { key: 'counselor', label: '辅导员' },
        ],
        emptyText: '暂无个人资料',
      },
    },
  },
}
